# Changes here will be overwritten by Copier
_commit: v1.0
_src_path: gh:igembitsgoa/igem-wiki-starter
author: caiorballarin
email: caioramosballarin@outlook.pt
iGEM_official_team_name: UNILA_LatAm
iGEM_team_name: UNILA_LatAm
year: 2021